default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: snapscandeals_development

test:
  <<: *default
  database: snapscandeals_test

production:
  <<: *default
  database: snapscandeals_production
  username: snapscandeals
  password: <%= ENV['PHOTOS_DATABASE_PASSWORD'] %>
